changes action to validate json only

diff --git a/.github/workflows/test_notebooks.yml b/.github/workflows/test_notebooks.yml
--- a/.github/workflows/test_notebooks.yml
+++ b/.github/workflows/test_notebooks.yml
@@ -4,6 +4,8 @@ on:
   pull_request:
     branches:
       - main
+    paths-ignore:
+    - '.github/**'
   workflow_dispatch:
 
 jobs:
@@ -17,14 +19,9 @@ jobs:
         uses: actions/setup-python@v4 # https://github.com/actions/setup-python/releases
         with:
           python-version: 3.11
-          
-      - name: Install Dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install nbqa pylint
 
-      - name: Test all Jupyter Notebooks with 'nbqa'
+      - name: Validate Jupyter Notebooks JSON Format
         run: |
-          for file in $(find . -name "*.ipynb"); do
-            nbqa pylint "$file" || { echo "Test failed for $file"; exit 1; }
-          done
+            for file in $(find . -name "*.ipynb"); do
+                python -c "import json; json.loads(open('$file').read())" || { echo "Validation failed for $file"; exit 1; }
+            done
