minor edit

diff --git a/.github/workflows/test_notebooks.yml b/.github/workflows/test_notebooks.yml
--- a/.github/workflows/test_notebooks.yml
+++ b/.github/workflows/test_notebooks.yml
@@ -1,33 +1,30 @@
-# this workflow re-uses the workflow 'github_action_trigger_submodule_pull_main.yml' in the brightway-documentation repository
 name: Test all Jupyter Notebooks for valid JSON (or else they might break the readthedocs.org build)
 
 on:
-    pull_request:
-        branches:
-            - main
-    workflow_dispatch:
-
+  pull_request:
+    branches:
+      - main
+  workflow_dispatch:
 
 jobs:
-    test-notebooks:
-        runs-on: ubuntu-latest
-
+  test-notebooks:
+    runs-on: ubuntu-latest
     steps:
-        - name: Checkout Repository
-          uses: actions/checkout@v4 # https://github.com/actions/checkout/releases
+      - name: Checkout Repository
+        uses: actions/checkout@v4 # https://github.com/actions/checkout/releases
 
-        - name: Set up Python
-          uses: actions/setup-python@v4 # https://github.com/actions/setup-python/releases
-          with:
-            python-version: 3.11
-            
-        - name: Install Dependencies
-          run: |
-            python -m pip install --upgrade pip
-            pip install nbqa pylint
+      - name: Set up Python
+        uses: actions/setup-python@v4 # https://github.com/actions/setup-python/releases
+        with:
+          python-version: 3.11
+          
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install nbqa pylint
 
-        - name: Test all Jupyter Notebooks with 'nbqa'
-          run: |
-            for file in $(find . -name "*.ipynb"); do
-                nbqa pylint "$file" || { echo "Test failed for $file"; exit 1; }
-            done
+      - name: Test all Jupyter Notebooks with 'nbqa'
+        run: |
+          for file in $(find . -name "*.ipynb"); do
+            nbqa pylint "$file" || { echo "Test failed for $file"; exit 1; }
+          done
